### PR TITLE
Customize window top offset and vertical margin

### PR DESCRIPTION
**Pull request by triqadafi**
I've added 2 option to adjust top margin and the vertical margin. 
image

I found that useful on tighter space. 
For example if you use small icon like me.

Here is the result:
image

### CODE REVIEW

**Comment by numbfall** [comment]
@triqadafi Can you create a build for this please? The dev is not going to pull this and after the recent windows update 22621.1413 the taskbar position is offset vertically. I think your changes will fix that.

**Comment by triqadafi** [comment]
@numbfall sure, I'm on the same windows version and didn't see any problem with my last build. I've just added it (https://github.com/triqadafi/TrafficMonitor/releases/tag/v1.84-release). Please have a try.

**Comment by numbfall** [comment]
> @numbfall sure, I'm on the same windows version and didn't see any problem with my last build. I've just added it (https://github.com/triqadafi/TrafficMonitor/releases/tag/v1.84-release). Please have a try.

I tried your release but i'm getting several missing dll errors. A few people are facing the issue I am as seen in recent issues. see #1546, #1543, and #1550

**Comment by triqadafi** [comment]
@numbfall sorry I couldn't find the missing dll error. Please add the details maybe the others can help.

Is it on the same version?
image

image

**Comment by numbfall** [comment]
Thank you for merging. Its working and I can set the vertical offset now. However, it's limited to 5 points only. Why is that? I needed more offset to center the taskbar monitor.

**Comment by triqadafi** [comment]
Thank you @zhongyang219 for merging.

@numbfall Sry I didn't expect that, the purpose is actually to make a small adjustment because small font look bit misaligned by 2-3 pixel. So, any suggestions about the maximum adjustment? Could you please post some screenshots?

**Comment by numbfall** [comment]
@triqadafi its okey. I ended up creating a pull request with increase from 5 to 20 pixels in offset range. see #1560. 

here is the default issue:
default
with your 5 pixels added :):
5px
I think I need at least 20 pixels offset to find the center of the taskbar.

side note: somebody removed the negative checkbox you added and added negative within the range which got merged to master as well. Also, I don't think less than -5 pixels is needed so I just increased the positive pixel offset max to 20.

**Pull request merged**
